# Generated by Django 5.2 on 2025-04-23 17:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrivateMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted_by_sender", models.BooleanField(default=False)),
                ("is_deleted_by_recipient", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Private Message",
                "verbose_name_plural": "Private Messages",
                "db_table": "private_message",
                "ordering": ["-created_at"],
            },
        ),
    ]
