# Generated by Django 5.2 on 2025-04-21 21:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("comment_reply", "Comment Reply"),
                            ("post_reply", "Post Reply"),
                            ("mention", "Mention"),
                            ("mod_action", "Moderator Action"),
                            ("vote_milestone", "Vote Milestone"),
                            ("welcome", "Welcome"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("comment", "Comment"),
                            ("message", "Message"),
                            ("community", "Community"),
                            ("user", "User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.UUIDField()),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("link_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
