# Generated by Django 5.2 on 2025-04-21 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("comment", "Comment")],
                        max_length=50,
                    ),
                ),
                ("content_id", models.UUIDField()),
                (
                    "vote_type",
                    models.SmallIntegerField(choices=[(-1, "Downvote"), (1, "Upvote")]),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "db_table": "vote",
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id"],
                        name="vote_content_2c6df6_idx",
                    ),
                    models.Index(
                        fields=["user", "content_type"], name="vote_user_id_a1da50_idx"
                    ),
                ],
                "unique_together": {("user", "content_type", "content_id")},
            },
        ),
    ]
