# Generated by Django 5.2 on 2025-04-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratelimit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_limits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-created_at"], name="audit_log_created_e49a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="audit_log_user_id_b57afc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_log_action_b32d4d_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"], name="audit_log_entity__c2633a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="email_verif_token_5274ac_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "-created_at"], name="email_verif_user_id_64e424_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["token"], name="password_re_token_e0c544_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(
                fields=["user", "-created_at"], name="password_re_user_id_f2744c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimit",
            index=models.Index(
                fields=["ip_address", "endpoint"], name="rate_limit_ip_addr_9c949d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimit",
            index=models.Index(
                fields=["user", "endpoint"], name="rate_limit_user_id_80ebee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimit",
            index=models.Index(
                fields=["expires_at"], name="rate_limit_expires_ed101d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["token"], name="refresh_tok_token_6c248f_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(
                fields=["user", "-created_at"], name="refresh_tok_user_id_5dd4b3_idx"
            ),
        ),
    ]
