# Generated by Django 5.2 on 2025-04-21 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("comment", "Comment"),
                            ("user", "User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.UUIDField()),
                ("reason", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BanAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appeal_type",
                    models.CharField(
                        choices=[
                            ("community_ban", "Community Ban"),
                            ("site_ban", "Site Ban"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField()),
                ("evidence", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True, null=True)),
                ("response_to_user", models.TextField(blank=True, null=True)),
                ("original_ban_reason", models.TextField(blank=True, null=True)),
                ("original_banned_until", models.DateTimeField(blank=True, null=True)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_appeals",
                        to="communities.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ban Appeal",
                "verbose_name_plural": "Ban Appeals",
                "db_table": "ban_appeal",
                "ordering": ["-created_at"],
            },
        ),
    ]
