# Generated by Django 5.2 on 2025-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
    ]
